(function(){
if(document.getElementById('profileModal'))return
var A=document.createElement.bind(document),q=function(id){return document.getElementById(id)},b=document.body
b.insertAdjacentHTML('beforeend','<style>.m{position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,.5);display:flex;align-items:center;justify-content:center;z-index:1000}.mc{background:#fff;padding:24px;border-radius:12px;width:420px;max-width:90vw;position:relative}.mc span{position:absolute;top:12px;right:16px;font-size:22px;cursor:pointer;color:#999}.fg{margin-bottom:12px}.fg label{display:block;font-size:13px;color:#666;margin-bottom:4px}.fg input{width:100%;padding:8px 10px;border:1px solid #ddd;border-radius:6px;font-size:14px}.mc .btn{width:100%;padding:10px;background:#667eea;color:#fff;border:none;border-radius:8px;font-size:15px;cursor:pointer}.msg{margin-top:10px;padding:10px;border-radius:6px;text-align:center}')
b.insertAdjacentHTML('beforeend','<div id=profileModal class=m><div class=mc><span onclick="pC()">\u00d7</span><h3>\u4e2a\u4eba\u8d44\u6599</h3><div class=fg><label>\u7528\u6237\u540d</label><input id=pU disabled></div><div class=fg><label>\u663e\u793a\u540d\u79f0</label><input id=pDN placeholder=\u8f93\u5165\u663e\u793a\u540d\u79f0></div><div class=fg><label>\u89d2\u8272</label><input id=pR disabled></div><button class=btn onclick=pS()>\u4fdd\u5b58</button><div id=pSM class=msg></div><hr style=margin:16px 0><h4>\u4fee\u6539\u5bc6\u7801</h4><div class=fg><label>\u65e7\u5bc6\u7801</label><input id=pOP type=password placeholder=\u8f93\u5165\u65e7\u5bc6\u7801></div><div class=fg><label>\u65b0\u5bc6\u7801</label><input id=pNP type=password placeholder=\u81f3\u5c114\u4e2a\u5b57\u7b26></div><div class=fg><label>\u786e\u8ba4\u65b0\u5bc6\u7801</label><input id=pNP2 type=password placeholder=\u518d\u6b21\u8f93\u5165></div><button class=btn onclick=pW()>\u4fee\u6539\u5bc6\u7801</button><div id=pWM class=msg></div></div></div><div id=cpModal class=m><div class=mc><span onclick="document.getElementById(\'cpModal\').style.display=\'none\'">\u00d7</span><h3>\u4fee\u6539\u7528\u6237\u5bc6\u7801</h3><p style=color:#666;font-size:13px>ID: <span id=cpU></span></p><div class=fg><label>\u65b0\u5bc6\u7801</label><input id=cpNP type=password></div><button class=btn onclick=cpW()>\u786e\u8ba4</button><div id=cpM class=msg></div></div></div>')
function pC(){profileModal.style.display='none'}
function pO(){profileModal.style.display='flex';fetch('/me',{credentials:'include'}).then(function(r){return r.json()}).then(function(u){pU.value=u.username||'';pDN.value=u.display_name||'';pR.value=u.role||''})}
function pS(){var dn=pDN.value.trim(),m=pSM;m.style.display='none';fetch('/me',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({display_name:dn})}).then(function(r){return r.json()}).then(function(d){d.ok?(m.textContent='\u5df2\u4fdd\u5b58',m.style.color='#27ae60'):(m.textContent=d.detail||'\u4fdd\u5b58\u5931\u8d25',m.style.color='#e74c3c');m.style.display='block';setTimeout(function(){m.style.display='none'},3000)})}
function pW(){var o=pOP.value,n=pNP.value,n2=pNP2.value,m=pWM;m.style.display='none';if(!o){m.textContent='\u8bf7\u8f93\u5165\u65e7\u5bc6\u7801';m.style.display='block';return}if(n.length<4){m.textContent='\u5bc6\u7801\u81f3\u5c114\u4e2a\u5b57\u7b26';m.style.display='block';return}if(n!=n2){m.textContent='\u4e24\u6b21\u8f93\u5165\u4e0d\u4e00\u81f4';m.style.display='block';return}fetch('/me/change_password',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({old_password:o,new_password:n})}).then(function(r){return r.json()}).then(function(d){d.ok?(m.textContent='\u5bc6\u7801\u5df2\u4fee\u6539',m.style.color='#27ae60',pOP.value='',pNP.value='',pNP2.value=''):(m.textContent=d.detail||'\u4fee\u6539\u5931\u8d25',m.style.color='#e74c3c');m.style.display='block';setTimeout(function(){m.style.display='none'},3000)})}
var _cu=0
function aCP(u){_cu=u;cpModal.style.display='flex';cpU.textContent=u;cpNP.value='';cpM.style.display='none'}
function cpW(){var n=cpNP.value,m=cpM;m.style.display='none';if(n.length<4){m.textContent='\u5bc6\u7801\u81f3\u5c114\u4e2a\u5b57\u7b26';m.style.display='block';return}fetch('/admin/user/'+_cu+'/change_password',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({new_password:n})}).then(function(r){return r.json()}).then(function(d){d.ok?(m.textContent='\u5df2\u4fee\u6539',m.style.color='#27ae60',setTimeout(function(){cpModal.style.display='none'},1200)):(m.textContent=d.detail||'\u5931\u8d25',m.style.color='#e74c3c');m.style.display='block'})}
})()

