
var pwdModalTargetUid = null;
function openPwdModal(uid){ var uname=''; var tbl=document.getElementById('userTableBody'); if(tbl){ var btns=tbl.querySelectorAll('[data-uid]'); for(var b=0;b<btns.length;b++){ if(btns[b].getAttribute('data-uid')==''+uid){ uname=btns[b].getAttribute('data-uname')||''; break; } } } pwdModalTargetUid=uid; document.getElementById('pwdModalTitle').textContent='修改密码 - '+(uname||'#'+uid); document.getElementById('pwdNewInput').value=''; document.getElementById('pwdConfirmInput').value=''; document.getElementById('pwdModalMsg').style.display='none'; document.getElementById('pwdModal').style.display='flex'; }
function closePwdModal(){ document.getElementById('pwdModal').style.display='none'; pwdModalTargetUid=null; }
function submitPwdModal(){ var np=document.getElementById('pwdNewInput').value; var cp=document.getElementById('pwdConfirmInput').value; var msg=document.getElementById('pwdModalMsg'); if(np.length<4){ msg.textContent='密码至少4个字符'; msg.style.display='block'; return; } if(np!==cp){ msg.textContent='两次输入的密码不一致'; msg.style.display='block'; return; } document.getElementById('pwdModalBtn').disabled=true; document.getElementById('pwdModalBtn').textContent='提交中...'; fetch('/admin/user/'+pwdModalTargetUid+'/change_password',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({new_password:np})}).then(function(r){return r.json();}).then(function(d){if(d.ok){alert('密码已修改');closePwdModal();}else{msg.textContent=d.detail||'修改失败';msg.style.display='block';}}).catch(function(){msg.textContent='请求失败';msg.style.display='block';}).finally(function(){document.getElementById('pwdModalBtn').disabled=false;document.getElementById('pwdModalBtn').textContent='确认修改';}); }
function openProfile(){ var m=document.getElementById('profileModal');m.style.display='flex';m.style.visibility='visible';m.style.opacity='1';setTimeout(function(){ fetch('/me',{credentials:'include'}).then(function(r){return r.json();}).then(function(u){ document.getElementById('profModalUser').value=u.username||''; document.getElementById('profModalDN').value=u.display_name||''; document.getElementById('profModalRole').value=u.role||''; }).catch(function(){}) },50); }
function closeProfile(){ document.getElementById('profileModal').style.display='none'; }
function saveProfileModal(){ var dn=document.getElementById('profModalDN').value.trim(); var msg=document.getElementById('profModalSaveMsg'); msg.style.display='none'; fetch('/me',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({display_name:dn})}).then(function(r){return r.json();}).then(function(d){if(d.ok){msg.textContent='已保存';msg.style.color='#27ae60';document.querySelector('[class*="user-area"]').textContent='?? '+(dn||'');}else{msg.textContent=d.detail||'保存失败';msg.style.color='#e74c3c';}msg.style.display='block';setTimeout(function(){msg.style.display='none';},3000);}).catch(function(){msg.textContent='请求失败';msg.style.color='#e74c3c';msg.style.display='block';}); }
function submitProfilePwdModal(){ var oldP=document.getElementById('profModalOldPwd').value; var newP=document.getElementById('profModalNewPwd').value; var newP2=document.getElementById('profModalNewPwd2').value; var msg=document.getElementById('profModalPwdMsg'); msg.style.display='none'; if(!oldP){msg.textContent='请输入旧密码';msg.style.display='block';return;} if(newP.length<4){msg.textContent='新密码至少4个字符';msg.style.display='block';return;} if(newP!==newP2){msg.textContent='两次输入的密码不一致';msg.style.display='block';return;} fetch('/me/change_password',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({old_password:oldP,new_password:newP})}).then(function(r){return r.json();}).then(function(d){if(d.ok){msg.textContent='密码已修改';msg.style.color='#27ae60';document.getElementById('profModalOldPwd').value='';document.getElementById('profModalNewPwd').value='';document.getElementById('profModalNewPwd2').value='';}else{msg.textContent=d.detail||'修改失败';msg.style.color='#e74c3c';}msg.style.display='block';setTimeout(function(){msg.style.display='none';},3000);}).catch(function(){msg.textContent='请求失败';msg.style.color='#e74c3c';msg.style.display='block';}); }
